linters:
  disable:
    - deadcode
    - unused
    - staticcheck
    - varcheck
    - noctx
    - gomnd
    - gochecknoglobals
    - goerr113
    - forcetypeassert
    - exhaustivestruct
    - wsl
    - cyclop
    - revive
    - unparam
    - nestif
    - lll
    - gosec
    - gocritic
    - funlen
    - goconst
    - forbidigo
    - dupl

    - golint
    - interfacer
    - maligned
    - scopelint

  enable-all: true